# Generated by Django 2.1.3 on 2018-12-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.IntegerField(choices=[(1, 'Lend'), (2, 'Borrow')], default=1),
        ),
    ]
